trainer:
  logger:
    - class_path: models.loggers.CustomWandbLogger
      init_args:
        tags:
          - mlp
          - synthetic
          - risk
          - case-control-sampling
  callbacks:
    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        patience: 20
        monitor: hp_metric
        min_delta: 0.002
        mode: max
        verbose: True
        check_finite: False
  max_epochs: 10
  check_val_every_n_epoch: 1
  log_every_n_steps: 10
  val_check_interval: 0.2
  enable_checkpointing: True
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  default_root_dir: .
data:
  wandb_artifact: anon/anon/metabric:latest
  val_split: 0.2
  batch_size: 128
  risk_set_size: 32
  num_workers: 1
model:
  head_layers: 2
  embedding_dim: 5
  head_hidden_dim: 128
  lr: 0.001
  only_covs: True
  cov_size: 3
  hidden_dropout_prob: 0.1
  batch_norm: True
