# wandb sweep
name: diffsort_svhn
program: /home/wildb/dev/projects/diffsurv/src/scripts/convdiffsort.py
method: grid
metric:
  name: val/c_index/all
  goal: maximize
parameters:
  seed_everything:
    values: [1,2,3,4,5] # will act as trails
  model.sorting_network:
    values: [odd_even, bitonic]
  data.risk_set_size:
    values: [2,4,8,16,32]
  data.batch_size:
    value: 100
  data.num_workers:
    value: -1
  trainer.strategy:
    value: ddp
  model.ignore_censoring:
    value: False
command:
  - ${env}
  - python3
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/convdiffsort.yml"
  - "--data.wandb_artifact"
  - anon/diffsurv/SVNH_beta1_cen0.3:v0
  - ${args}
project: diffsurv
entity: anon
