# wandb sweep
method: bayes
program: scripts/mlpdiffsort.py
metric:
  name: hp_metric
  goal: maximize
parameters:
  model.ignore_censoring:
    value: False
  model.lr:
    distribution: log_uniform
    min: -9.210340371976182 # 0.0001
    max: -3.506557897319982 # 0.03
  model.final_lr:
    distribution: log_uniform
    min: -9.210340371976182 # 0.0001
    max: 2.302585092994046 # 10
  model.head_layers:
    value: 2
  model.head_hidden_dim:
    value: 1024
  model.hidden_dropout_prob:
    value: 0.1
  model.steepness:
    min: 1
    max: 50
  model.art_lambda:
    value: 0.0 # doesn't matter for cauchy
  model.distribution:
    value: cauchy
  model.sorting_network:
    value: bitonic
  model.use_buckets:
    value: True
  data.batch_size:
    value: 64
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/mlpdiffsort.yaml"
  - "--data.wandb_artifact"
  - "anon/diffsurv/pysurv_square_independent_0.3.pt:latest"
  - ${args}
project: diffsurv
entity: anon
