# wandb sweep
program: scripts/mlpdiffsort.py
method: random
metric:
  name: val/loss
  goal: minimize
parameters:
  model.ignore_censoring:
    value: True
  model.lr:
    min: 0.0001
    max: 0.03
  model.head_layers:
    value: 2
  model.head_hidden_dim:
    value: 1024
  model.hidden_dropout_prob:
    value: 0.1
  model.steepness:
    min: 10
    max: 50
  model.art_lambda:
    value: 0.0 # doesn't matter for cauchy
  model.distribution:
    value: cauchy
  model.sorting_network:
    values: [odd_even, bitonic]
  data.batch_size:
    value: 64
command:
  - ${env}
  - python3
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/mlpdiffsort.yaml"
  - "--data.wandb_artifact"
  - "anon/diffsurv/pysurv_square_0.3.pt:v4"
  - ${args}
project: diffsurv
entity: anon
