# wandb sweep
name: nwtco_diffsort
method: grid
program: scripts/mlpdiffsort.py
metric:
  name: hp_metric
  goal: maximize
parameters:
  model.batch_norm:
    value: False
  model.lr:
    values: [0.001, 0.005, 0.0001]
  model.head_layers:
    values: [1, 2]
  model.head_hidden_dim:
    values: [64, 128, 256]
  model.hidden_dropout_prob:
    values: [0, 0.1, 0.2]
  data.batch_size:
    values: [16, 64, 128]
  data.risk_set_size:
    values: [2, 5, 10, 20, 30]
  model.steepness:
    values: [10, 20, 30]
  model.sorting_network:
    values: [bitonic, odd_even]
command:
  - ${env}
  - python3
  - ${program}
  - fit
  - "--config"
  - "jobs/configs/mlpdiffsort.yaml"
  - "--data.wandb_artifact"
  - "anon/diffsurv/nwtco.pt:latest"
  - ${args}
project: diffsurv
entity: anon
